import Head from "next/head";
import Button from "../components/Button";

export default function Home() {
  return (
    <div className="main_content">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button
        type="button"
        buttonStyle="btn__primary__solid"
        buttonSize="btn__large"
      >
        Click Me
      </Button>
      <Button
        link="https://mariuszgolik-portfolio.vercel.app/"
        type="button"
        buttonStyle="btn__primary__solid"
        buttonSize="btn__medium"
      >
        Click Me
      </Button>
      <Button
        link="https://mariuszgolik-portfolio.vercel.app/"
        target="_blank"
        type="button"
        buttonStyle="btn__primary__solid"
        buttonSize="btn__small"
      >
        Click Me
      </Button>
    </div>
  );
}
